# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, verbose_name='query text')),
                ('parent', models.CharField(max_length=200, verbose_name='query parent')),
                ('active', models.BooleanField(verbose_name='currently active')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_deactivated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
